import events
import keys
import types
from .devices import ENCODER as ENCODER, Encoder as Encoder, HOST as HOST, HostEvents as HostEvents, JOYSTICK as JOYSTICK, Joystick as Joystick, KEYPAD as KEYPAD, Keypad as Keypad, POINTER as POINTER, Touch as Touch
from _typeshed import Incomplete

DEFAULT_REFRESH_MS: int
SERVICE_TICK_MS: int

class _RefreshClaim:
    def __init__(self, app) -> None: ...
    def release(self) -> None: ...

class _PollingClaim:
    def __init__(self, app) -> None: ...
    def release(self) -> None: ...

class _RefreshPaused:
    def __init__(self, app) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None): ...

class App:
    events = events
    keys = keys
    HOST = HOST
    POINTER = POINTER
    ENCODER = ENCODER
    KEYPAD = KEYPAD
    JOYSTICK = JOYSTICK
    @classmethod
    def current(cls): ...
    devices: Incomplete
    host_dev: Incomplete
    touch_dev: Incomplete
    keypad_dev: Incomplete
    encoder_dev: Incomplete
    joystick_dev: Incomplete
    def __init__(self, board_config=None, *, displays=None, host_read=None, touch_read=None, touch_rotation_table=None, refresh_period=None) -> None: ...
    @property
    def strategy(self): ...
    @property
    def displays(self): ...
    @property
    def primary(self): ...
    @property
    def quit_requested(self): ...
    @property
    def before_quit(self): ...
    @before_quit.setter
    def before_quit(self, value) -> None: ...
    @property
    def timers(self): ...
    def add_display(self, drv): ...
    def remove_display(self, drv) -> None: ...
    def add_touch(self, read, *, display=None, rotation_table=None): ...
    def add_keypad(self, read): ...
    def add_encoder(self, read, *, button_read=None, button: int = 2): ...
    def add_joystick(self, joystick_driver, *, emulate_digital=None, digital_threshold: float = 0.5): ...
    def register(self, dev) -> None: ...
    def unregister(self, dev) -> None: ...
    def on(self, event_type_or_list, callback=None): ...
    def off(self, event_type_or_list, callback) -> None: ...
    def every(self, ms=None, callback=None, *, period=None, name=None): ...
    def on_tick(self, callback, period=..., **_ignored): ...
    def stop_timers(self) -> None: ...
    stop_timer = stop_timers
    def pause_refresh(self): ...
    def resume_refresh(self) -> None: ...
    def refresh_paused(self): ...
    def pause_polling(self): ...
    def resume_polling(self) -> None: ...
    def poll(self): ...
    def run(self, tick_ms=...): ...
    def run_async(self, coro_or_fn): ...
    def request_quit(self, code=None) -> None: ...
