from _typeshed import Incomplete

__all__ = ['DisplayDriver', 'alloc_buffer', 'byteswap', 'capabilities', 'color332', 'color565', 'color565_swapped', 'color_rgb']

byteswap: Incomplete

def capabilities(): ...
def alloc_buffer(size): ...
def color565(r, g=None, b=None): ...
def color565_swapped(r, g: int = 0, b: int = 0): ...
def color332(r, g, b): ...
def color_rgb(color): ...

class FrameClock:
    name: Incomplete
    count: int
    last: Incomplete
    def __init__(self, period_ms, name=None) -> None: ...
    @property
    def period_ms(self): ...
    @period_ms.setter
    def period_ms(self, value) -> None: ...
    @property
    def running(self): ...
    def subscribe(self, fn): ...
    def unsubscribe(self, fn) -> None: ...
    def stop(self) -> None: ...

class _FpsMeter:
    now: Incomplete
    diff: Incomplete
    def __init__(self, now, diff) -> None: ...
    mark: Incomplete
    win_us: int
    win_frames: int
    win_present: int
    win_flushes: int
    win_pixels: int
    frame_us: int
    frame_max: int
    last_fps: Incomplete
    seconds: float
    frames: int
    present_us: float
    flushes: int
    pixels: int
    def reset(self) -> None: ...
    def frame(self, t, dt) -> None: ...
    def flush(self, t, dt, pixels) -> None: ...
    def snapshot(self): ...

class DisplayDriver:
    needs_refresh: bool
    refresh_period_ms: int
    share_framebuffer: bool
    quit_chord: Incomplete
    @property
    def frame_clock(self): ...
    def framebuffers(self) -> None: ...
    byteswap: Incomplete
    touch_scale: float
    def __init__(self, *, quiet: bool = False) -> None: ...
    def __del__(self) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def rotation(self) -> int: ...
    @rotation.setter
    def rotation(self, value) -> None: ...
    @property
    def touch_device(self) -> object: ...
    @touch_device.setter
    def touch_device(self, value) -> None: ...
    def fill(self, color): ...
    def scroll(self, dx, dy) -> None: ...
    def disable_auto_byteswap(self, value: bool) -> bool: ...
    @property
    def requires_byteswap(self) -> bool: ...
    def blit_transparent(self, buf: memoryview, x: int, y: int, w: int, h: int, key: int): ...
    @property
    def vscroll(self) -> int: ...
    @vscroll.setter
    def vscroll(self, y) -> None: ...
    def set_vscroll(self, tfa: int = 0, bfa: int = 0) -> None: ...
    @property
    def tfa(self) -> int: ...
    @property
    def vsa(self) -> int: ...
    @property
    def bfa(self) -> int: ...
    def translate_point(self, point) -> tuple: ...
    def scroll_by(self, value) -> None: ...
    def scroll_to(self, value) -> None: ...
    @property
    def tfa_area(self): ...
    @property
    def vsa_area(self): ...
    @property
    def bfa_area(self): ...
    def measure_fps(self, on: bool = True): ...
    def frame_done(self) -> None: ...
    def fps(self): ...
    def fps_reset(self) -> None: ...
    def fps_print(self, seconds: int = 5) -> None: ...
    def vscrdef(self, tfa: int, vsa: int, bfa: int) -> None: ...
    def vscsad(self, vssa: int | None = None) -> int: ...
    @property
    def power(self) -> bool: ...
    @power.setter
    def power(self, value: bool) -> None: ...
    @property
    def brightness(self) -> float: ...
    @brightness.setter
    def brightness(self, value: float) -> None: ...
    def invert_colors(self, value: bool) -> None: ...
    def reset(self) -> None: ...
    def hard_reset(self) -> None: ...
    def soft_reset(self) -> None: ...
    def sleep_mode(self, value: bool) -> None: ...
    def deinit(self) -> None: ...
    def quit(self, code: int = 0, force: bool = False) -> None: ...
    def force_quit(self, code: int = 0) -> None: ...
    def show(self, *args, **kwargs) -> None: ...
