from displaydev import DisplayDriver as DisplayDriver

def desktop_work_area(display_index: int = 0): ...
def fit_scale_to_desktop(width, height, scale, desktop_w, desktop_h, *, margin=..., chrome_w: int = 0, chrome_h: int = 0): ...
def notify_board_config_scale_override(driver_name, requested, fitted, *, quiet: bool = False) -> None: ...

class DesktopDisplay(DisplayDriver):
    def vscrdef(self, tfa: int, vsa: int, bfa: int) -> None: ...
    def vscsad(self, vssa=None) -> int: ...

class FrameRecorderMixin:
    @property
    def frame_recording(self) -> bool: ...
    def open_frame_recorder(self, path, *, fps: int = 12, width=None, height=None): ...
    def close_frame_recorder(self): ...
