from _typeshed import Incomplete
from displaydev import color_rgb as color_rgb
from displaydev._desktop import DesktopDisplay as DesktopDisplay
from displaydev._domkeys import enrich_mod as enrich_mod, key_to_keycode as key_to_keycode, mod_mask as mod_mask

class JNDevices:
    image: Incomplete
    def __init__(self, display_drv) -> None: ...
    def read(self): ...
    def update_buffer(self, pil_image) -> None: ...

class JNDisplay(DesktopDisplay):
    needs_refresh: bool
    quit_chord: Incomplete
    color_depth: int
    touch_scale: float
    def __init__(self, width, height, *, quiet: bool = False) -> None: ...
    def get_events(self): ...
    def init(self) -> None: ...
    def fill_rect(self, x, y, w, h, c): ...
    def blit_rect(self, buf, x, y, w, h): ...
    def pixel(self, x, y, c): ...
    def render(self, render_rect=None): ...
    def show(self, _timer=None) -> None: ...
