from _typeshed import Incomplete
from displaydev._desktop import DesktopDisplay, FrameRecorderMixin

__all__ = ['poll_event', 'get_events', 'PGDisplay']

def poll_event(): ...
def get_events(): ...

class PGDisplay(FrameRecorderMixin, DesktopDisplay):
    needs_refresh: bool
    quit_chord: Incomplete
    color_depth: Incomplete
    touch_scale: Incomplete
    app: Incomplete
    get_events: Incomplete
    def __init__(self, width: int = 320, height: int = 240, rotation: int = 0, color_depth: int = 16, title: str = 'displaydev', scale: float = 1.0, window_flags=..., *, quiet: bool = False) -> None: ...
    def init(self) -> None: ...
    def blit_rect(self, buffer: memoryview, x: int, y: int, w: int, h: int): ...
    def fill_rect(self, x: int, y: int, w: int, h: int, c: int): ...
    def pixel(self, x: int, y: int, c: int): ...
    def capture_rgb(self): ...
    def render(self, renderRect=None) -> None: ...
    def show(self, _timer=None) -> None: ...
    def quit(self, code: int = 0, force: bool = False) -> None: ...
