from _typeshed import Incomplete
from displaydev import color_rgb as color_rgb
from displaydev._desktop import DesktopDisplay as DesktopDisplay, FrameRecorderMixin as FrameRecorderMixin

def poll_event(): ...
def get_events(): ...
def retcheck(retvalue) -> None: ...

class SDLDisplay(FrameRecorderMixin, DesktopDisplay):
    needs_refresh: bool
    quit_chord: Incomplete
    color_depth: Incomplete
    touch_scale: float
    app: Incomplete
    get_events: Incomplete
    def __init__(self, width: int = 320, height: int = 240, rotation: int = 0, color_depth: int = 16, title: str = 'SDL2 Display', scale: float = 1.0, window_flags=..., render_flags=..., x=..., y=..., *, quiet: bool = False) -> None: ...
    def init(self) -> None: ...
    def blit_rect(self, buffer: memoryview, x: int, y: int, w: int, h: int): ...
    def fill_rect(self, x: int, y: int, w: int, h: int, c: int): ...
    def pixel(self, x: int, y: int, c: int): ...
    def render(self, renderRect=None) -> None: ...
    def show(self, _timer=None) -> None: ...
    def capture_rgb(self): ...
    def quit(self, code: int = 0, force: bool = False) -> None: ...
    def force_quit(self, code: int = 0) -> None: ...
