from _typeshed import Incomplete
from displaydev._desktop import DesktopDisplay as DesktopDisplay
from displaydev._domkeys import enrich_mod as enrich_mod, key_to_keycode as key_to_keycode, mod_mask as mod_mask
from displaydev.fbdisplay import FBDisplay as FBDisplay

class WasmDevices:
    def __init__(self, canvas_id) -> None: ...
    def read(self): ...
    def clear(self) -> None: ...

class WasmDisplay(DesktopDisplay, FBDisplay):
    needs_refresh: bool
    refresh_period_ms: int
    quit_chord: Incomplete
    get_events: Incomplete
    def __init__(self, width: int = 320, height: int = 240, canvas_id: str = 'display_canvas', *, quiet: bool = False) -> None: ...
    def init(self) -> None: ...
    def show(self, _timer=None) -> None: ...
