def bind_lazy(ns, peripherals_mod): ...
def audio_provider(): ...
def pcm_out(format=None, **kwargs): ...
def pcm_in(format=None, **kwargs): ...
def audio_out(format=None, **kwargs): ...
def env_set(name, value) -> None: ...
def env_bool(name, default: bool = False): ...
def env_get(name, default=None): ...
def env_int(name, default: int = 0): ...
def env_float(name, default: float = 0.0): ...
