import types
from ._ticks import ticks_add as ticks_add, ticks_diff as ticks_diff, ticks_ms as ticks_ms
from _typeshed import Incomplete

ONE_SHOT: int
PERIODIC: int

def wake_from_source(safe: bool = False) -> None: ...
def deliver(): ...
def next_delay_ms(): ...
def schedule(fn, arg) -> None: ...

class Timer:
    ONE_SHOT = ONE_SHOT
    PERIODIC = PERIODIC
    yield_cap: int
    id: Incomplete
    name: Incomplete
    fired: int
    missed: int
    late_max: int
    last: Incomplete
    error: Incomplete
    def __init__(self, id: int = -1, **kwargs) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: types.TracebackType | None): ...
    def init(self, *, mode=..., freq: int = -1, period: int = -1, callback=None, hard: bool = False) -> None: ...
    def deinit(self) -> None: ...
    cancel = deinit
    def reschedule(self, delay_ms) -> None: ...
    @property
    def period(self): ...
    @property
    def mode(self): ...
    @property
    def callback(self): ...
    @property
    def running(self): ...
    @property
    def due_in(self): ...

def hold(): ...

class _Hold:
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: types.TracebackType | None): ...

def sleep_ms(ms) -> None: ...
def pump(): ...
def run_until(pred, tick_ms: int = 10) -> None: ...
def keepalive(flag: bool = True) -> None: ...
def alive(): ...
def timers(): ...
def stop_all() -> None: ...
def reset_stats() -> None: ...
def source(): ...
def stop_source() -> None: ...
def info(): ...
