AMBIENT: str
EXIT_HOOK: str
NONE: str

def ambient(): ...
def interactive(): ...
def batch(): ...
def on_exit(fn): ...
def mark_crashed() -> None: ...
def claim() -> None: ...
def release() -> None: ...
def on_stop(fn) -> None: ...
def ensure_installed(): ...
def strategy(): ...
