name: str
delivery: str
wakes_blocking: bool

def start(wake) -> None: ...
def arm(delay_ms) -> None: ...
def cancel() -> None: ...
def stop() -> None: ...
def poll() -> None: ...
def sleep_ms(ms) -> None: ...
