from ._ticks import ticks_add as ticks_add, ticks_diff as ticks_diff, ticks_ms as ticks_ms

name: str
delivery: str
wakes_blocking: bool

def start(wake) -> None: ...
def arm(delay_ms) -> None: ...
def cancel() -> None: ...
def stop() -> None: ...
