import ctypes

name: str
delivery: str
wakes_blocking: bool

class _timespec(ctypes.Structure): ...
class _itimerspec(ctypes.Structure): ...
class _sigval(ctypes.Union): ...
class _sigevent(ctypes.Structure): ...

def start(wake) -> None: ...
def arm(delay_ms) -> None: ...
def cancel() -> None: ...
def stop() -> None: ...
